//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.20.0
//     from Assets/MLGWorks/MLGWorks.DevConsole/Resources/DevConsoleInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace MLGWorks.DevConsole
{
    /// <summary>
    /// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/MLGWorks/MLGWorks.DevConsole/Resources/DevConsoleInputActions.inputactions".
    /// </summary>
    /// <remarks>
    /// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
    /// </remarks>
    /// <example>
    /// <code>
    /// using namespace UnityEngine;
    /// using UnityEngine.InputSystem;
    ///
    /// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
    /// public class Example : MonoBehaviour, MyActions.IPlayerActions
    /// {
    ///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
    ///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
    ///
    ///     void Awake()
    ///     {
    ///         m_Actions = new MyActions_Actions();              // Create asset object.
    ///         m_Player = m_Actions.Player;                      // Extract action map object.
    ///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
    ///     }
    ///
    ///     void OnDestroy()
    ///     {
    ///         m_Actions.Dispose();                              // Destroy asset object.
    ///     }
    ///
    ///     void OnEnable()
    ///     {
    ///         m_Player.Enable();                                // Enable all actions within map.
    ///     }
    ///
    ///     void OnDisable()
    ///     {
    ///         m_Player.Disable();                               // Disable all actions within map.
    ///     }
    ///
    ///     #region Interface implementation of MyActions.IPlayerActions
    ///
    ///     // Invoked when "Move" action is either started, performed or canceled.
    ///     public void OnMove(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
    ///     }
    ///
    ///     // Invoked when "Attack" action is either started, performed or canceled.
    ///     public void OnAttack(InputAction.CallbackContext context)
    ///     {
    ///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
    ///     }
    ///
    ///     #endregion
    /// }
    /// </code>
    /// </example>
    public partial class @DevConsoleInputActions: IInputActionCollection2, IDisposable
    {
        /// <summary>
        /// Provides access to the underlying asset instance.
        /// </summary>
        public InputActionAsset asset { get; }

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public @DevConsoleInputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""DevConsoleInputActions"",
    ""maps"": [
        {
            ""name"": ""DevConsole"",
            ""id"": ""981ffcef-ca94-45de-8257-39f2f4590b0a"",
            ""actions"": [
                {
                    ""name"": ""ToggleConsole"",
                    ""type"": ""Button"",
                    ""id"": ""6a425238-a0cf-4059-8da1-22a4e091994c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""SubmitCommand"",
                    ""type"": ""Button"",
                    ""id"": ""37687ab0-02d4-4df7-ad8d-eb2f0b86a5b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""AutoComplete"",
                    ""type"": ""Button"",
                    ""id"": ""a6e5aacc-f6be-4e32-9d84-a4a5fe45b34f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""CommandHistoryPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""6f6a7a0f-3632-4c1b-8e48-47f58d9d2b11"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                },
                {
                    ""name"": ""CommandHistoryNext"",
                    ""type"": ""Button"",
                    ""id"": ""f1ba06c2-bb2e-427a-9f8d-d75e99b7df21"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7380c86e-3d77-4def-9311-e49584b72bc4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleConsole"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fac13c3-7fa4-4023-9ecb-8c5b2908e74b"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitCommand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""212ea648-9169-454a-baab-a4cca1f27ede"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoComplete"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a7c6304-9c3a-4132-b718-53a7425de839"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandHistoryPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b4287eb-ac09-46e4-b97c-619a5da29fbb"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CommandHistoryNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // DevConsole
            m_DevConsole = asset.FindActionMap("DevConsole", throwIfNotFound: true);
            m_DevConsole_ToggleConsole = m_DevConsole.FindAction("ToggleConsole", throwIfNotFound: true);
            m_DevConsole_SubmitCommand = m_DevConsole.FindAction("SubmitCommand", throwIfNotFound: true);
            m_DevConsole_AutoComplete = m_DevConsole.FindAction("AutoComplete", throwIfNotFound: true);
            m_DevConsole_CommandHistoryPrevious = m_DevConsole.FindAction("CommandHistoryPrevious", throwIfNotFound: true);
            m_DevConsole_CommandHistoryNext = m_DevConsole.FindAction("CommandHistoryNext", throwIfNotFound: true);
        }

        ~@DevConsoleInputActions()
        {
            UnityEngine.Debug.Assert(!m_DevConsole.enabled, "This will cause a leak and performance issues, DevConsoleInputActions.DevConsole.Disable() has not been called.");
        }

        /// <summary>
        /// Destroys this asset and all associated <see cref="InputAction"/> instances.
        /// </summary>
        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
        public void Enable()
        {
            asset.Enable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
        public void Disable()
        {
            asset.Disable();
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
        public IEnumerable<InputBinding> bindings => asset.bindings;

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // DevConsole
        private readonly InputActionMap m_DevConsole;
        private List<IDevConsoleActions> m_DevConsoleActionsCallbackInterfaces = new List<IDevConsoleActions>();
        private readonly InputAction m_DevConsole_ToggleConsole;
        private readonly InputAction m_DevConsole_SubmitCommand;
        private readonly InputAction m_DevConsole_AutoComplete;
        private readonly InputAction m_DevConsole_CommandHistoryPrevious;
        private readonly InputAction m_DevConsole_CommandHistoryNext;
        /// <summary>
        /// Provides access to input actions defined in input action map "DevConsole".
        /// </summary>
        public struct DevConsoleActions
        {
            private @DevConsoleInputActions m_Wrapper;

            /// <summary>
            /// Construct a new instance of the input action map wrapper class.
            /// </summary>
            public DevConsoleActions(@DevConsoleInputActions wrapper) { m_Wrapper = wrapper; }
            /// <summary>
            /// Provides access to the underlying input action "DevConsole/ToggleConsole".
            /// </summary>
            public InputAction @ToggleConsole => m_Wrapper.m_DevConsole_ToggleConsole;
            /// <summary>
            /// Provides access to the underlying input action "DevConsole/SubmitCommand".
            /// </summary>
            public InputAction @SubmitCommand => m_Wrapper.m_DevConsole_SubmitCommand;
            /// <summary>
            /// Provides access to the underlying input action "DevConsole/AutoComplete".
            /// </summary>
            public InputAction @AutoComplete => m_Wrapper.m_DevConsole_AutoComplete;
            /// <summary>
            /// Provides access to the underlying input action "DevConsole/CommandHistoryPrevious".
            /// </summary>
            public InputAction @CommandHistoryPrevious => m_Wrapper.m_DevConsole_CommandHistoryPrevious;
            /// <summary>
            /// Provides access to the underlying input action "DevConsole/CommandHistoryNext".
            /// </summary>
            public InputAction @CommandHistoryNext => m_Wrapper.m_DevConsole_CommandHistoryNext;
            /// <summary>
            /// Provides access to the underlying input action map instance.
            /// </summary>
            public InputActionMap Get() { return m_Wrapper.m_DevConsole; }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
            public void Enable() { Get().Enable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
            public void Disable() { Get().Disable(); }
            /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
            public bool enabled => Get().enabled;
            /// <summary>
            /// Implicitly converts an <see ref="DevConsoleActions" /> to an <see ref="InputActionMap" /> instance.
            /// </summary>
            public static implicit operator InputActionMap(DevConsoleActions set) { return set.Get(); }
            /// <summary>
            /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <param name="instance">Callback instance.</param>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
            /// </remarks>
            /// <seealso cref="DevConsoleActions" />
            public void AddCallbacks(IDevConsoleActions instance)
            {
                if (instance == null || m_Wrapper.m_DevConsoleActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_DevConsoleActionsCallbackInterfaces.Add(instance);
                @ToggleConsole.started += instance.OnToggleConsole;
                @ToggleConsole.performed += instance.OnToggleConsole;
                @ToggleConsole.canceled += instance.OnToggleConsole;
                @SubmitCommand.started += instance.OnSubmitCommand;
                @SubmitCommand.performed += instance.OnSubmitCommand;
                @SubmitCommand.canceled += instance.OnSubmitCommand;
                @AutoComplete.started += instance.OnAutoComplete;
                @AutoComplete.performed += instance.OnAutoComplete;
                @AutoComplete.canceled += instance.OnAutoComplete;
                @CommandHistoryPrevious.started += instance.OnCommandHistoryPrevious;
                @CommandHistoryPrevious.performed += instance.OnCommandHistoryPrevious;
                @CommandHistoryPrevious.canceled += instance.OnCommandHistoryPrevious;
                @CommandHistoryNext.started += instance.OnCommandHistoryNext;
                @CommandHistoryNext.performed += instance.OnCommandHistoryNext;
                @CommandHistoryNext.canceled += instance.OnCommandHistoryNext;
            }

            /// <summary>
            /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
            /// </summary>
            /// <remarks>
            /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
            /// </remarks>
            /// <seealso cref="DevConsoleActions" />
            private void UnregisterCallbacks(IDevConsoleActions instance)
            {
                @ToggleConsole.started -= instance.OnToggleConsole;
                @ToggleConsole.performed -= instance.OnToggleConsole;
                @ToggleConsole.canceled -= instance.OnToggleConsole;
                @SubmitCommand.started -= instance.OnSubmitCommand;
                @SubmitCommand.performed -= instance.OnSubmitCommand;
                @SubmitCommand.canceled -= instance.OnSubmitCommand;
                @AutoComplete.started -= instance.OnAutoComplete;
                @AutoComplete.performed -= instance.OnAutoComplete;
                @AutoComplete.canceled -= instance.OnAutoComplete;
                @CommandHistoryPrevious.started -= instance.OnCommandHistoryPrevious;
                @CommandHistoryPrevious.performed -= instance.OnCommandHistoryPrevious;
                @CommandHistoryPrevious.canceled -= instance.OnCommandHistoryPrevious;
                @CommandHistoryNext.started -= instance.OnCommandHistoryNext;
                @CommandHistoryNext.performed -= instance.OnCommandHistoryNext;
                @CommandHistoryNext.canceled -= instance.OnCommandHistoryNext;
            }

            /// <summary>
            /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="DevConsoleActions.UnregisterCallbacks(IDevConsoleActions)" />.
            /// </summary>
            /// <seealso cref="DevConsoleActions.UnregisterCallbacks(IDevConsoleActions)" />
            public void RemoveCallbacks(IDevConsoleActions instance)
            {
                if (m_Wrapper.m_DevConsoleActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            /// <summary>
            /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
            /// </summary>
            /// <remarks>
            /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
            /// </remarks>
            /// <seealso cref="DevConsoleActions.AddCallbacks(IDevConsoleActions)" />
            /// <seealso cref="DevConsoleActions.RemoveCallbacks(IDevConsoleActions)" />
            /// <seealso cref="DevConsoleActions.UnregisterCallbacks(IDevConsoleActions)" />
            public void SetCallbacks(IDevConsoleActions instance)
            {
                foreach (var item in m_Wrapper.m_DevConsoleActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_DevConsoleActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        /// <summary>
        /// Provides a new <see cref="DevConsoleActions" /> instance referencing this action map.
        /// </summary>
        public DevConsoleActions @DevConsole => new DevConsoleActions(this);
        /// <summary>
        /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "DevConsole" which allows adding and removing callbacks.
        /// </summary>
        /// <seealso cref="DevConsoleActions.AddCallbacks(IDevConsoleActions)" />
        /// <seealso cref="DevConsoleActions.RemoveCallbacks(IDevConsoleActions)" />
        public interface IDevConsoleActions
        {
            /// <summary>
            /// Method invoked when associated input action "ToggleConsole" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnToggleConsole(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "SubmitCommand" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnSubmitCommand(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "AutoComplete" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnAutoComplete(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "CommandHistoryPrevious" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCommandHistoryPrevious(InputAction.CallbackContext context);
            /// <summary>
            /// Method invoked when associated input action "CommandHistoryNext" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
            /// </summary>
            /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
            /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
            void OnCommandHistoryNext(InputAction.CallbackContext context);
        }
    }
}
